### ISSUE TITLE
Tests accessing Application Settings fails on NET45 with SerializationException : TestContextProvider is not marked as serializable

### ISSUE THREAD

**Issue by ssg47** [LightBDD/LightBDD#73] opened 2017-10-16 13:14 UTC
#### Description

I've just run my first test in a real project and got this:

	SCENARIO: [SCENARIO-1] Get userProperties scenario
	  STEP 1/3: GIVEN template method...
	  STEP 1/3: GIVEN template method (Failed after 383ms)
	  SCENARIO RESULT: Failed after 441ms
		Step 1: System.Runtime.Serialization.SerializationException : Type 'LightBDD.NUnit2.Implementation.TestContextProvider' in assembly 'LightBDD.NUnit2, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
			at System.AppDomain.GetHostEvidence(Type type)
			at System.Security.Policy.AppDomainEvidenceFactory.GenerateEvidence(Type evidenceType)
			at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
			at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
	FEATURE FINISHED: UserProperties feature
	NUnit VS Adapter 2.1.1.0 executing tests is finished

And I'm not sure what to do about it.  Did I cause this by doing something wrong?

**Comment by Suremaker** [comment] 2017-10-16 14:11
Hello,

It is difficult to identify what is going on without access to the Visual Studio. I wonder if your code is doing anything with separate AppDomains? The first thing I found on the topic is that: https://github.com/nunit/nunit/issues/137
Also how is the test executed? Is it failing in Visual Studio or nunit console?

**Comment by ssg47** [comment] 2017-10-16 14:36
I've run it in both with the same result.  Now that I've run it in NUnit, I can see a more detailed StackTrace.  (And I've realised it was in Test Explorer as well (hidden away, at the bottom).  I need to go through that and see what might have triggered it.

My code isn't using separate AppDomains but [NUnit does](http://nunit.org/docs/2.6.4/assemblyIsolation.html).

I've also found this [Mitigation: Deserialization of Objects Across App Domains](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-deserialization-of-objects-across-app-domains) which may be related.  I'm not using the `<LogicalCallContext>` but I am using .NET configuration.  I'm going to have to re-read that when my brain is fresh.  :-(

**Comment by Suremaker** [comment] 2017-10-16 15:50
I cannot help you much at this moment, but if you have a possibility to use .net46 or higher instead .net45 for your test project, can you try to do following thing:
1. Update test project to .net46
2. Uninstall LightBDD.NUnit2/Framewor/Core packages and reinstall them to ensure that dlls are taken from net46 directory of LightBDD
3. Try to rerun tests.

You have mentioned the `LogicalCallContext` and I may be using it [here](https://github.com/LightBDD/LightBDD/blob/master/src/LightBDD.Framework/ExecutionContext/AsyncLocalContext.cs) for projects targetting net45.
Please let me know if that made any difference.
It is interesting however what is different in your real project that makes it not working...

**Comment by ssg47** [comment] 2017-10-17 07:18
I tried updating to .NET 4.6 and that didn't help.  I've managed to recreate the issue in a new solution:

1. Create a new .NET 4.5.2 Console project `LightBDDConfigException1`.
2. Open the Project Properties, select Settings and click on the link to create a Settings file.
4. Make the Name of the setting `Setting1`, the scope `Application` and the Value `A string`.
5. Close the Project Properties window.
6. Add a class, `Class1`.
7. Make the content:

        public String GetSetting()
        {
            var setting1 = "A string";
            //var setting1 = Properties.Settings.Default.Setting1;
            return setting1;
        }

    (Keep the line commented-out for now.)
8. Add a .NET 4.5.2 Class Library project `<LightBddFixtures1>`.
9. Add a reference from `<LightBddFixtures1>` to `<LightBDDConfigException1>`.
10. Add the NuGet packages NUnit v2.6.4 and LightBDD.NUnit2.
11. Delete the default `Class1.cs` file.
12. Add > New Item... > LightBDD > LightBDD.NUnit2: Feature Test Class called `My_feature1.cs`.
13. Edit `My_feature1.Steps.cs`.
14. Remove the Asserts from the Given_ and When_ methods, leaving them empty.
15. Make the Then_ method:

        private void Then_template_method()
        {
            var instance = new Class1();
            Assert.That(instance.GetSetting(), Is.EqualTo("A string"));
        }
16. Remove the `Template_extended_scenario` method.
17. Run All tests.  Results are:
	------ Run test started ------
	NUnit VS Adapter 2.1.1.0 executing tests is started
	Loading tests from C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBddFixtures1\bin\Debug\LightBddFixtures1.dll
	Run started: C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBddFixtures1\bin\Debug\LightBddFixtures1.dll
	FEATURE: [FEAT-1] My feature1
	  In order to 
	  As a
	  I want to 
	SCENARIO: [SCENARIO-1] Template basic scenario
	  STEP 1/3: GIVEN template method...
	  STEP 1/3: GIVEN template method (Passed after 16ms)
	  STEP 2/3: WHEN template method...
	  STEP 2/3: WHEN template method (Passed after <1ms)
	  STEP 3/3: THEN template method...
	  STEP 3/3: THEN template method (Passed after 13ms)
	  SCENARIO RESULT: Passed after 68ms
	FEATURE FINISHED: My feature1
	NUnit VS Adapter 2.1.1.0 executing tests is finished
	========== Run test finished: 1 run (0:00:03.3001851) ==========

18. Swap the comments in `Class1.GetSetting` to:

        public String GetSetting()
        {
            //var setting1 = "A string";
            var setting1 = Properties.Settings.Default.Setting1;
            return setting1;
        }
19. Run All tests.  Results are:
	------ Run test started ------
	NUnit VS Adapter 2.1.1.0 executing tests is started
	Loading tests from C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBddFixtures1\bin\Debug\LightBddFixtures1.dll
	Run started: C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBddFixtures1\bin\Debug\LightBddFixtures1.dll
	FEATURE: [FEAT-1] My feature1
	  In order to 
	  As a
	  I want to 
	SCENARIO: [SCENARIO-1] Template basic scenario
	  STEP 1/3: GIVEN template method...
	  STEP 1/3: GIVEN template method (Passed after 16ms)
	  STEP 2/3: WHEN template method...
	  STEP 2/3: WHEN template method (Passed after <1ms)
	  STEP 3/3: THEN template method...
	  STEP 3/3: THEN template method (Failed after 100ms)
	  SCENARIO RESULT: Failed after 176ms
		Step 3: System.Runtime.Serialization.SerializationException : Type 'LightBDD.NUnit2.Implementation.TestContextProvider' in assembly 'LightBDD.NUnit2, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
			at System.AppDomain.GetHostEvidence(Type type)
			at System.Security.Policy.AppDomainEvidenceFactory.GenerateEvidence(Type evidenceType)
			at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
			at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
	FEATURE FINISHED: My feature1
	NUnit VS Adapter 2.1.1.0 executing tests is finished
	========== Run test finished: 1 run (0:00:03.4872174) ==========

20. The full stack trace from the test adapter is:

	Test Name:	Template_basic_scenario
	Test FullName:	LightBddFixtures1.My_feature1.Template_basic_scenario
	Test Source:	C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBddFixtures1\My_feature1.cs : line 18
	Test Outcome:	Failed
	Test Duration:	0:00:00.228

	Result StackTrace:	
	at System.AppDomain.GetHostEvidence(Type type)
	at System.Security.Policy.AppDomainEvidenceFactory.GenerateEvidence(Type evidenceType)
	at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
	at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
	at System.Security.Policy.Evidence.RawEvidenceEnumerator.MoveNext()
	at System.Security.Policy.Evidence.EvidenceEnumerator.MoveNext()
	at System.Configuration.ClientConfigPaths.GetEvidenceInfo(AppDomain appDomain, String exePath, String& typeName)
	at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(AppDomain appDomain, String exePath)
	at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
	at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
	at System.Configuration.Internal.ConfigurationManagerInternal.System.Configuration.Internal.IConfigurationManagerInternal.get_ExeProductName()
	at System.Configuration.ApplicationSettingsBase.get_Initializer()
	at System.Configuration.ApplicationSettingsBase.CreateSetting(PropertyInfo propInfo)
	at System.Configuration.ApplicationSettingsBase.EnsureInitialized()
	at System.Configuration.ApplicationSettingsBase.get_Properties()
	at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
	at System.Configuration.SettingsBase.get_Item(String propertyName)
	at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
	at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
	at LightBDDConfigException1.Properties.Settings.get_Setting1() in C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBDDConfigException1\Properties\Settings.Designer.cs:line 31
	at LightBDDConfigException1.Class1.GetSetting() in C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBDDConfigException1\Class1.cs:line 14
	at LightBddFixtures1.My_feature1.Then_template_method() in C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBddFixtures1\My_feature1.Steps.cs:line 23
	at LightBDD.Framework.Scenarios.Basic.Implementation.BasicStepCompiler.StepExecutor.Execute(Object context, Object[] args)
	at LightBDD.Core.Extensibility.Implementation.ScenarioRunner.InvocationResultTransformer.<InvokeAsync>d__5.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at LightBDD.Core.Execution.Implementation.RunnableStep.<InvokeStepMethodAsync>d__22.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at LightBDD.Core.Execution.Implementation.RunnableStep.<InvokeStepMethodAsync>d__22.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at LightBDD.Core.Execution.Implementation.RunnableStep.<InvokeStepAsync>d__19.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at LightBDD.Framework.Commenting.Implementation.StepCommentingDecorator.<ExecuteAsync>d__0.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at LightBDD.Core.Execution.Implementation.RunnableStep.<TimeMeasuredInvokeAsync>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at LightBDD.Core.Execution.Implementation.RunnableStep.<RunAsync>d__16.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at LightBDD.Core.Execution.Implementation.RunnableScenario.ProcessExceptions(ExceptionCollector exceptionCollector)
	at LightBDD.Core.Execution.Implementation.RunnableScenario.<RunAsync>d__17.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at LightBDD.Core.Extensibility.Implementation.ScenarioRunner.RunSynchronously()
	at LightBDD.Framework.Scenarios.Basic.Implementation.BasicScenarioRunner.RunScenario(Action[] steps)
	at LightBDD.Framework.Scenarios.Basic.BasicScenarioExtensions.RunScenario(IBddRunner runner, Action[] steps)
	at LightBddFixtures1.My_feature1.Template_basic_scenario() in C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBddFixtures1\My_feature1.cs:line 19
	Result Message:	System.Runtime.Serialization.SerializationException : Type 'LightBDD.NUnit2.Implementation.TestContextProvider' in assembly 'LightBDD.NUnit2, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.

I've done a similar version where the test fixture project is just an NUnit v2.6.4 project with a single fixture:

    [TestFixture]
    public class Class1Fixtures
    {
        [Test]
        public void TakeAction_whenCalled_loadsSetting()
        {
            var instance = new Class1();

            Assert.That(instance.GetSetting(), Is.EqualTo("A string"));
        }
    }
and that doesn't exhibit the issue.

**Comment by Suremaker** [comment] 2017-10-17 08:52
Thank you for finding it out. I will investigate what can be done when I come back from holidays after 22nd. I have not noticed this issue before.

In the meantime I wonder if it would be possible to somehow enforce nunit to run tests in the same app domain as hosting process.
There are some docs how to control it in console/GUI: http://nunit.org/docs/2.6.4/assemblyIsolation.html
I am not sure how to change it for VS test adapter though.

The last idea I have to check would be to try LightBDD.NUnit3 to check if that would work as all the runners for nunit3 has been rewritten - but I am not sure if you can use nunit3 in your project.

**Comment by ssg47** [comment] 2017-10-17 10:12
Last idea first: running under NUnit3 has the same issue.  The Output > Tests window is different:

	------ Run test started ------
	NUnit Adapter 3.8.0.0: Test execution started
	Running all tests in C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBddFixtures1\bin\Debug\LightBddFixtures1.dll
	NUnit3TestExecutor converted 1 of 1 NUnit test cases
	NUnit Adapter 3.8.0.0: Test execution complete
	========== Run test finished: 1 run (0:00:01.8941059) ==========

but the exception is similar (except for <InvokeAsync> and similar, NUnit3 references):

	Test Name:	Template_basic_scenario
	Test FullName:	LightBddFixtures1.My_feature1.Template_basic_scenario
	Test Source:	C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBddFixtures1\My_feature1.cs : line 18
	Test Outcome:	Failed
	Test Duration:	0:00:00.233

	Result StackTrace:	
	at System.AppDomain.GetHostEvidence(Type type)
	   at System.Security.Policy.AppDomainEvidenceFactory.GenerateEvidence(Type evidenceType)
	   at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
	   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
	   at System.Security.Policy.Evidence.RawEvidenceEnumerator.MoveNext()
	   at System.Security.Policy.Evidence.EvidenceEnumerator.MoveNext()
	   at System.Configuration.ClientConfigPaths.GetEvidenceInfo(AppDomain appDomain, String exePath, String& typeName)
	   at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(AppDomain appDomain, String exePath)
	   at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
	   at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
	   at System.Configuration.Internal.ConfigurationManagerInternal.System.Configuration.Internal.IConfigurationManagerInternal.get_ExeProductName()
	   at System.Configuration.ApplicationSettingsBase.get_Initializer()
	   at System.Configuration.ApplicationSettingsBase.CreateSetting(PropertyInfo propInfo)
	   at System.Configuration.ApplicationSettingsBase.EnsureInitialized()
	   at System.Configuration.ApplicationSettingsBase.get_Properties()
	   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
	   at System.Configuration.SettingsBase.get_Item(String propertyName)
	   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
	   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
	   at LightBDDConfigException1.Properties.Settings.get_Setting1() in C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBDDConfigException1\Properties\Settings.Designer.cs:line 31
	   at LightBDDConfigException1.Class1.GetSetting() in C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBDDConfigException1\Class1.cs:line 14
	   at LightBddFixtures1.My_feature1.Then_template_method() in C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBddFixtures1\My_feature1.Steps.cs:line 23
	   at LightBDD.Framework.Scenarios.Basic.Implementation.BasicStepCompiler.StepExecutor.Execute(Object context, Object[] args)
	   at LightBDD.Core.Extensibility.Implementation.ScenarioRunner.InvocationResultTransformer.<InvokeAsync>d__5.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at LightBDD.Core.Execution.Implementation.RunnableStep.<InvokeStepMethodAsync>d__22.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at LightBDD.Core.Execution.Implementation.RunnableStep.<InvokeStepMethodAsync>d__22.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at LightBDD.Core.Execution.Implementation.RunnableStep.<InvokeStepAsync>d__19.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at LightBDD.Framework.Commenting.Implementation.StepCommentingDecorator.<ExecuteAsync>d__0.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at LightBDD.Core.Execution.Implementation.RunnableStep.<TimeMeasuredInvokeAsync>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at LightBDD.Core.Execution.Implementation.RunnableStep.<RunAsync>d__16.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at LightBDD.Core.Execution.Implementation.RunnableScenario.ProcessExceptions(ExceptionCollector exceptionCollector)
	   at LightBDD.Core.Execution.Implementation.RunnableScenario.<RunAsync>d__17.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at LightBDD.Core.Extensibility.Implementation.ScenarioRunner.RunSynchronously()
	   at LightBDD.Framework.Scenarios.Basic.Implementation.BasicScenarioRunner.RunScenario(Action[] steps)
	   at LightBDD.Framework.Scenarios.Basic.BasicScenarioExtensions.RunScenario(IBddRunner runner, Action[] steps)
	   at LightBddFixtures1.My_feature1.Template_basic_scenario() in C:\Users\Public\Visual Studio\Investigations\LightBDDConfigException1\LightBddFixtures1\My_feature1.cs:line 19
	Result Message:	System.Runtime.Serialization.SerializationException : Type 'LightBDD.NUnit3.Implementation.TestContextProvider' in assembly 'LightBDD.NUnit3, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.

I wanted to look into that one because it will take quite a bit of work to move the Solution to NUnit3, which would need some planning - I will do it but ideally not now.

**Comment by ssg47** [comment] 2017-10-17 10:34
As for the NUnit assembly isolation, my NUnit GUI settings were (and are, again) as the default shown on [Settings Dialog](http://nunit.org/docs/2.6.4/settingsDialog.html) under the heading Test Loader Settings - Assembly Isolation.

I read the page you referenced as describing how to get more isolation, not less, but I tried the other options, anyway, with the same results (except with 'Merge tests across assemblies', when they didn't run as all because it couldn't find the LightBDD assembly attribute).

For now, I will rework the tests to fake the configuration code so that I can get the tests to run.  If you can fix this later, I'll remove the fakes.

**Comment by Suremaker** [comment] 2017-10-18 07:23
OK, I'll investigate the issue and come back to you

**Comment by Suremaker** [comment] 2017-10-25 21:14
Hello,
I created a set of projects to recreate the issue and check how given test frameworks behave and I found that:
* tests fails for all runners if project targets .NET 4.5.X
* tests passes for all runners if project targets .NET 4.6.X or higher

Here is a sample solution presenting it: 
[SettingTests.zip](https://github.com/LightBDD/LightBDD/files/1416171/SettingTests.zip)

And a screenshot: 
![image](https://user-images.githubusercontent.com/1894621/32023319-c8f2f3c8-b9d0-11e7-8bb1-efaa2586bf14.png)

So most likely the problem is related to the issue you have found around the `<LogicalCallContext>` that I am using in LightBDD for .NET 4.5.X

---

I will investigate a fix for LightBDD .NET 4.5.X and will let you know about it.

As an alternative, you can upgrade your test project to .NET 4.6 (if your infrastructure allows it) and you should be able to run the tests (as the sample project shows). I've seen from the comments above that you tried it and found it was failing, but my guess is that after bumping up the project target framework you have not reinstalled the LightBDD packages and they were still pointing to `..\packages\LightBDD.XXX.2.3.0\lib\net45\LightBDD.XXX.dll`

**Comment by Suremaker** [comment] 2017-10-30 08:49
Fixed in LightBDD 2.3.1

**Closed by Suremaker** 2017-10-30 08:49 UTC
Labels: bug
